### PR TITLE
Cover card - option to change the up/down button icon

### PR DESCRIPTION
**Pull request by tj57**
This is a simple change giving the option to change the up/down button icon on the cover card.

image

### CODE REVIEW

**Comment by Clooos** [comment]
Nice! Thank you! 

Can you also add this to the documentation? 😄

**Comment by tj57** [comment]
@Clooos Documentation updated.

**Comment by Clooos** [comment]
Thanks a lot! I will wait a bit for a new stable version then I will pull it.

**Comment by Clooos** [comment]
I've added it to the new v1.5.0, thanks again! 🍻

**Pull request merged**
