### PR TITLE
Conditional visibility for sub-buttons

### PR DESCRIPTION
**Pull request by MrBearPresident**
Tested: Yes

image

Used some code from the standard HA-UI, but since you work type-less I had to rework some.

### CODE REVIEW

**Comment by MrBearPresident** [comment]
#787

This will be solved.

**Comment by Clooos** [comment]
Hi! Haven't tested it yet but that looks truly amazing! Thank you so much!

Just a suggestion for the text under "Visibility" on your screenshot, replace "entity" with "sub-button", this makes more sense in that case.

**Comment by Clooos** [comment]
Just tried it and this is trully amazing! I know that you used the HA source code and I always tried to avoid that, but nice adaptation!

By seeing this I think that it would be great to use this for the pop-up trigger condition, I'm not asking you to do it (unless you want to) but that was a thought 😃 And also the entity dropdown is so much better than mine, I should replace it everywhere!

And I've just changed that for a better visual consistency:

image


Thank you again! This is a great PR!

**Comment by MrBearPresident** [comment]
The door for conditional something is open now...
You want conditional colors, this will be possible...

Why I reused the ha-source code? Because I want to give to most consistent UX I can. 
This is should be a well known condition selector.

**Comment by Clooos** [comment]
And I totally agree with you, I love doing things my way, but sometime it's better to keep something that just works 👌

By seeing this I wonder if we could also have the default HA tap action editor, mine is terrible compared to the default one. I tried in the past with no great success 😅

**Comment by alexanderdominicnesbitt** [comment]
Screenshot_20250114_214313_Home Assistant


Hey guys, just updated to this release but not seeing the visibility options. Any ideas?

**Comment by Clooos** [comment]
Hi! Have you cleared your app/browser cache?

**Comment by alexanderdominicnesbitt** [comment]
I redownloaded from Hacs and all good. Thanks

________________________________

**Pull request merged**
